<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta name="title" content="Terms and Conditions - Hyderabad Constructions">
    <meta name="description" content="Terms and Conditions - Hyderabad Constructions">
    <meta name="keywords" content="Hyderabad Constructions">

    <meta name="robots" content="index, follow">
    <meta name="language" content="English">
    <meta name="revisit-after" content="30 days">
    <meta name="author" content="Hyderabad Constructions">

    <link rel="icon" type="image/x-icon" href="/images/favicon.png">
    <link rel="apple-touch-icon" href="/images/favicon.png">

    <meta name="theme-color" content="#c96b2a">
    <meta name="apple-mobile-web-app-status-bar" content="#c96b2a">

    <title>Terms and Conditions - Hyderabad Constructions</title>
    
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="assets/css/style.css">
    <script src="assets/js/theme-config.js"></script>
</head>

<body class="bg-[#FCFCF7] text-ink">

    <?php include 'includes/navbar.php'; ?>

    <section class="bg-[#FCFCF7] flex flex-col items-center w-full">
        <div
            class="flex flex-col items-center justify-start gap-5 px-4 pt-10 pb-2 w-full max-w-[768px] xl:max-w-[1440px] xl:px-20 xl:pt-14">
            <div class="text-center">
                <h1 class="font-display text-3xl md:text-4xl font-semibold text-ink mb-5">Terms and Conditions</h1>
                <p class="text-base text-muted">Last updated: May 08, 2026</p>
            </div>
            <picture class="w-full mt-4">
                <img alt="Terms of Use Banner" loading="lazy"
                    class="h-[190px] w-full object-cover rounded-lg xl:rounded-xl xl:h-[368px]"
                    src="assets/images/terms-and-conditions.jpg"
                    onerror="this.style.background='#e0d8cc'" >
            </picture>
        </div>
    </section>

    <section class="w-full bg-[#FCFCF7] flex flex-col items-center pb-20">
        <div class="w-full max-w-[768px] xl:max-w-[1440px] px-4 xl:px-20 policy-content pt-10">

            <!-- Opening uppercase notices -->
            <p class="uppercase-notice">BY ACCESSING OR USING THIS PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS OF
                USE, PRIVACY POLICY AND SUCH OTHER AGREEMENTS, AS MAY BE ADOPTED BY US FROM TIME TO TIME. PLEASE READ
                THESE TERMS CAREFULLY BEFORE ENTERING INTO A TRANSACTION ON THIS PLATFORM.</p>
            <p class="uppercase-notice">
                THIS DOCUMENT IS AN ELECTRONIC RECORD UNDER THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES THEREUNDER.
                THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL
                SIGNATURES.</p>
             <p class="uppercase-notice">
                THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) OF THE INFORMATION TECHNOLOGY
                (INTERMEDIARIES GUIDELINES) RULES, 2021 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY
                POLICY AND TERMS OF USE FOR ACCESS TO OR USAGE OF THIS PLATFORM.</p>

            <hr class="section-divider">

            <!-- Section 1 -->
            <h2>1. General</h2>

            <p>1.1 The Platform is owned and operated by Hyderabad Constructions Platforms Limited (<strong>"Hyderabad Constructions"</strong>), having
                its registered corporate office at 6th Floor, Grande Palladium, 175 CST Road, Kalina, Santacruz (East),
                Mumbai – 400098.</p>

            <p>1.2 Your use of the Platform is governed by the following Terms of Use as applicable and the Agreements
                (defined below) provided separately on the Platform and which are or may hereafter be incorporated
                herein by way of reference (<strong>"Terms of Use"</strong>). If You transact on the Platform, You shall
                also be subject to the Agreements that are applicable to the Platform for such Transaction. By mere use
                of the Platform, You shall be contracting with Hyderabad Constructions, and these Terms of Use including the Agreements
                constitute Your binding obligations, with Hyderabad Constructions.</p>

            <p>1.3 For the purpose of these Terms of Use, wherever the context so requires:</p>

            <p>(a) <strong>"Affiliate"</strong> shall mean, with respect to each party, any person or entity directly or
                indirectly through one or more intermediary Controlling, Controlled by, or under direct or indirect
                common Control with a party. "Control", "Controlled" or "Controlling" shall mean, with respect to any
                person or entity, any circumstance in which such person or entity is controlled by another person or
                entity by virtue of the latter person or entity controlling the composition of the board of directors or
                managers or owning the largest or controlling percentage of the voting securities of such person/entity
                or otherwise controlling the other;</p>

            <p>(b) <strong>"Platform"</strong> shall mean this internet based e-commerce services platform <a
                    href="https://hyderabadconstructions.in/" target="_blank">https://hyderabadconstructions.in/</a> and/or an application,
                website and/or web-page (including but not limited to any web app, marketing landing page(s), and/or
                iOS/Android app or any other app that the buyer may be using to access/communicate with Hyderabad Constructions)
                (<strong>"Platform"</strong>), owned and/or operated, directly or indirectly, by Hyderabad Constructions;</p>

            <p>(c) <strong>"GST"</strong> means the goods and service tax as levied under the Central Goods and Services
                Tax Act and Rules (CGST), Integrated Goods and Services Tax Act and Rules (IGST), State Goods and
                Services Tax Acts and Rules (SGST) levied by the States, Union Territory Goods and Services Tax Act and
                Rules (UTGST) levied by the Union Territories, and all allied cesses, duties and taxes;</p>

            <p>(d) <strong>"Hyderabad Constructions Companies"</strong> shall mean and include Hyderabad Constructions Steel Limited, Hyderabad Constructions Cement, Hyderabad Constructions Paints
                Limited, and their respective subsidiaries, associate companies, joint ventures, and Affiliates, whether
                existing now or established at any time in the future.</p>

            <p>(e) <strong>"KYC Documents"</strong> means such 'know your customer' documents as may be required to be
                submitted to Hyderabad Constructions from time to time;</p>

            <p>(f) <strong>"Profile"</strong> means the individually identifiable profile of User created at the time of
                registering on the Platform;</p>

            <p>(g) <strong>"Transaction"</strong> means the process of booking and availing Services (defined
                hereinafter);</p>

            <p>(h) <strong>"User Content"</strong> means content including data or information of You, including Your
                rating, comments, reviews in relation to the services offered or the Platform, suggestions, questions or
                other information and includes any material that is generated, as a whole or in part, on the Platform,
                including, communication between Users, analytics and reports, trends, patterns, notes, messages,
                emails, designs, catalogues, posts and other communication that Users provide or receive, through
                Platform and any other project related information and documentation shared with the User;</p>

            <p>(i) <strong>"We"</strong> or <strong>"Us"</strong> or <strong>"Our"</strong> or <strong>"Hyderabad Constructions
                    One"</strong> means Hyderabad Constructions or any of its subsidiaries or Affiliates; and</p>

            <p>(j) <strong>"You"</strong> or <strong>"Your"</strong> or <strong>"User/s"</strong> means a legal person
                who is given access to use the Platform for the purpose of availing services on the Platform.</p>

            <p>(k) <strong>"Contractors"</strong> or <strong>"Service Providers"</strong> means the independent
                third-party construction contractors listed on the Platform and offering construction services to the
                Users.</p>

            <p>1.4 By accessing or using this Platform, You agree to be bound by these Terms of Use, the <a
                    href="privacy-policy.html">Privacy Policy</a> and related agreements
                (<strong>"Agreements"</strong>). In the event that there are any conflicts between (a) the Privacy
                Policy and any other Agreements (other than these Terms of Use), the Privacy Policy shall take
                precedence to the extent of the conflict; (b) these Terms of Use and any other notices, disclaimers or
                guidelines appearing on the Platform, these Terms of Use shall take precedence to the extent of the
                conflict. These Terms of Use together with the Privacy Policy, and the other Agreements, and all other
                notices, disclaimers, guidelines appearing on the Platform from time to time, constitute the entire
                agreement upon which You are allowed to access and avail the Services.</p>

            <p>1.5 The monies on the Platform are displayed in Indian Rupees. The price unless specified otherwise is
                exclusive of all applicable taxes including GST, customs duty, excise duty or other tax or levy that the
                User may be required to remit in connection with such a Transaction.</p>

            <hr class="section-divider">

            <!-- Section 2 -->
            <h2>2. Services</h2>

            <p>2.1 Hyderabad Constructions owns and operates the Platform, wherein Hyderabad Constructions, using its proprietary technology and
                platform services, connects its Users with Contractors and facilitates delivery of building construction
                services (<strong>"Services"</strong>).</p>

            <p>2.2 The User understands and agrees that the Platform services offered by Hyderabad Constructions are not absolute or
                unconditional. Such services are subject to repudiation by Hyderabad Constructions at any time and without any
                obligation to assign or provide any reason for such repudiation and without any consent from the User
                and without any liability or any obligation towards the User. You understand and agree that Hyderabad Constructions has
                the right to cancel any Transaction (a) for any reason, or (b) under an order or instruction from any
                statutory, quasi-judicial or judicial authority.</p>

            <hr class="section-divider">

            <!-- Section 3 -->
            <h2>3. Access to the Platform</h2>

            <p>3.1 You may access and use the Platform only if You are 18 (eighteen) years of age or older and are
                legally capable of entering into a binding contract as per applicable law, including, in particular, the
                Indian Contract Act, 1872. Hyderabad Constructions reserves the right to terminate Your registration and / or refuse to
                provide You access to the Platform if it is brought to Hyderabad Constructions's notice or if it is discovered that You
                are a minor, insolvent or in any manner barred from entering into a contract. Hyderabad Constructions reserves the right
                to refuse access to use the Services offered at the Platform to new Users or to terminate access granted
                to existing Users at any time without according any reasons for doing so.</p>

            <p>3.2 On the condition that You comply with these Terms of Use and the Agreements, We grant You a personal,
                non-exclusive, non-transferable, revocable, limited privilege to access and use the Platform. Hyderabad Constructions
                further grants You a limited licence to access and make personal use of the Platform, but not to
                download (other than page caching) or modify it, or any portion of it. This license does not include any
                resale or commercial use of this Platform or its contents; any derivative use of this Platform or its
                contents; any downloading or copying of account information for the benefit of another person; or any
                use of data mining, robots, or similar data gathering and extraction tools.</p>

            <hr class="section-divider">

            <!-- Section 4 -->
            <h2>4. Your Profile and Your Information</h2>

            <p>4.1 Users are required to register on the Platform by submitting the requisite documents and information
                and subsequently creating a Profile. Upon successful registration, Users will be issued a username and
                password which are linked to Your Profile. These are non-transferable. Please keep this information
                confidential as You are responsible for all acts or omissions committed on the Platform using Your
                username or password and for all the information / content posted under Your Profile. Users are
                prohibited from selling, trading, or otherwise transferring their Profiles to other persons.
                Representatives of Hyderabad Constructions may assist the Users with creating their account and registering them on the
                Platform.</p>

            <p>4.2 By creating a Profile, You confirm that the information in Your Profile is accurate, genuine and will
                be regularly updated and You shall immediately notify Us of any unauthorised use of Your Profile or any
                other breach of these Terms of Use or security known to You.</p>

            <p>4.3 If You provide any information that is untrue, inaccurate, not current or incomplete (or becomes
                untrue, inaccurate, not current or incomplete), or Hyderabad Constructions has reasonable grounds to suspect that such
                information is untrue, inaccurate, not current or incomplete, Hyderabad Constructions has the right to suspend or
                terminate Your Profile and refuse any and all current or future use of the Platform / Services (or any
                portion thereof).</p>

            <p>4.4 By creating a Profile, You will be responsible for maintaining the confidentiality and security of
                Your Profile, and are fully responsible for all activities that are carried out through Your Profile.
                You agree to (a) immediately notify Hyderabad Constructions of any unauthorized use of Your Profile or any other breach
                of security, and (b) ensure that You exit from Your Profile at the end of each session. Hyderabad Constructions cannot
                and will not be liable for any loss or damage arising from Your failure to comply with these
                requirements.</p>

            <p>4.5 Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform.
                It is your responsibility to ensure that Your mobile phone number and your email address is up to date
                on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail
                address changes by updating the same on the Platform through a onetime password verification.</p>

            <p>4.6 You agree that Hyderabad Constructions shall not be liable or responsible for the activities or consequences of use
                or misuse of any information that occurs in Your Profile in cases, including, where You have failed to
                update Your revised mobile phone number and/or e-mail address on the Platform.</p>

            <p>4.7 Hyderabad Constructions does not pre-screen Your Profile information or User Content. However, Hyderabad Constructions at its
                discretion and in accordance with applicable law may monitor any content or information posted by You
                and may remove any User Content from the Platform if Hyderabad Constructions determines in its sole discretion that such
                User Content is in violation of these Terms of Use or any applicable law. Where Hyderabad Constructions removes User
                Content from the Platform, Hyderabad Constructions will make reasonable efforts to inform the User who had posted such
                User Content. Such actions do not in any manner, negate or dilute Hyderabad Constructions's position as an intermediary
                or impose any liability on Hyderabad Constructions with respect to User Content.</p>

            <p>4.8 Depending upon the nature of Services You wish to avail from the Platform, You may be required to
                provide certain personal information and Hyderabad Constructions may collect certain personal information. Your
                provision of, and Hyderabad Constructions's collection, storage, use, disclosure and otherwise dealing of such personal
                information shall be governed by Hyderabad Constructions's privacy policy.</p>

            <p>4.9 Further, You authorize Hyderabad Constructions Companies and Hyderabad Constructions to:</p>
            <ul>
                <li>(a) collect, use, share, process and store all information, including personal information, provided
                    by You and Your access information including the IP address, IMEI number and MAC address of the
                    computer / device from where the Platform was accessed;</li>
                <li>(b) either directly, or through third parties, verify and confirm information in Your Profile;</li>
                <li>(c) contact You using the information in Your Profile and provide promotional materials that may be
                    of interest to You;</li>
                <li>(d) use any and all of the information provided by You to create Your Profile; and</li>
                <li>(e) modify, limit or delete Your Profile as may be required.</li>
            </ul>

            <hr class="section-divider">

            <!-- Section 5 -->
            <h2>5. Electronic Execution and Communications</h2>

            <p>5.1 When You use the Platform or send emails or other data, information or communication to Us, You agree
                and understand that You are communicating with Hyderabad Constructions Companies and Hyderabad Constructions through electronic records and
                You consent to receive communications via electronic records or otherwise from Hyderabad Constructions Companies and Hyderabad Constructions
                periodically to the electronic or residential address provided to us at the time of registration, and as
                and when required. Hyderabad Constructions Companies and Hyderabad Constructions may communicate with You by email or by such other mode of
                communication, electronic or otherwise.</p>

            <p>5.2 Hyderabad Constructions will undertake reasonable efforts to ensure that availability of the Platform will be
                uninterrupted and that transmissions will be error-free. However, due to the inherent nature of the
                internet, this cannot be guaranteed. The Platform may also be occasionally suspended or restricted to
                carry out repairs, maintenance, or the introduction of new facilities, upgradations or services at any
                time without prior notice.</p>

            <hr class="section-divider">

            <!-- Section 6 -->
            <h2>6. Platform for Transaction and Communications</h2>

            <p>6.1 The Platform is only for providing a venue for communication and payment services and it is agreed
                that the contract in respect of the construction services shall be a strictly bipartite works contract
                between the Users and the Contractors. At no time shall any right, title or interest over the items vest
                with Hyderabad Constructions nor shall Hyderabad Constructions have any obligations or liabilities in respect of such contract, except
                for certain facilitative, transaction support and payment-related services as provided in agreements
                entered into between Users, Contractors, franchisees and Us.</p>

            <p>6.2 All commercial / contractual terms are offered by and agreed to between Users and Contractors alone.
                The commercial / contractual terms include without limitation price for construction of the residential
                project, purchase of materials, shipping costs for the materials, date, period and mode of delivery,
                warranties related to goods and services and after sales services related to goods and services.
                Platform does not have any control or determines or advises or in any way involves itself in the
                offering or acceptance of such commercial / contractual terms between Users and Contractors. Without
                prejudice to the foregoing, the Platform may provide certain transaction support services to Users and
                Contractors of the Platform.</p>

            <p>6.3 Hyderabad Constructions is not responsible for any non-performance or breach of any contract entered into between
                Users and Contractors. Hyderabad Constructions cannot and does not guarantee, warrant, assure or ensure that the Users
                and Contractors will perform, undertake, consume or conclude any transaction on the Platform. Platform
                shall not and is not required to mediate or resolve any dispute or disagreement between the Users and
                Contractors.</p>

            <p>6.4 Platform does not make any representation or warranty as to the attributes (such as quality, worth,
                marketability, etc.) of the services proposed to be offered on the Platform. You are advised to
                independently verify the bona fides of any particular Contractor that you choose to deal with on the
                Platform and use your best judgment in that behalf. In particular, Platform does not implicitly or
                explicitly support or endorse any particular construction services on the Platform. Platform accepts no
                liability for any errors or omissions, whether on behalf of itself or third parties.</p>

            <hr class="section-divider">

            <!-- Section 7 -->
            <h2>7. Use of the Platform</h2>

            <p>7.1 You agree not to host, display, upload, modify, publish, transmit, update, share or otherwise make
                available on the Platform any information, that:</p>
            <ul>
                <li>(a) belongs to another person and over which you have no right;</li>
                <li>(b) harms minors in any way;</li>
                <li>(c) contains content or other material protected by intellectual property laws unless You own or
                    control the rights thereto or have received all necessary consents;</li>
                <li>(d) defames, abuses, harasses, stalks, hurts religious or ethnic sentiments of, threatens or
                    otherwise violates the legal rights of others;</li>
                <li>(e) is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, paedophilic,
                    libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable,
                    disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any
                    manner whatever;</li>
                <li>(f) is false, inaccurate or misleading in any way; infringes any patent, trademark, copyright or
                    other proprietary rights;</li>
                <li>(g) violates any law for the time being in force; deceives or misleads the addressee about the
                    origin of such messages or communicates any information which is grossly offensive or menacing in
                    nature;</li>
                <li>(h) abets or assists with impersonating another person; contains software viruses or any other
                    computer codes, files, or programs designed to interrupt, destroy, or limit the functionality of any
                    computer resource;</li>
                <li>(i) conducts or forwards surveys, contests, pyramid schemes or chain letters;</li>
                <li>(j) solicits gambling or engages in any gambling activity which we, at our sole discretion, believe
                    is or could be construed as being illegal;</li>
                <li>(k) interferes with another's use and enjoyment of the Platform;</li>
                <li>(l) creates profiles or provides content that promotes escort services or prostitution;</li>
                <li>(m) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations
                    with foreign states, or disrupts public order or causes incitement to the commission of any
                    cognisable offence;</li>
                <li>(n) uses any other internet service to send or post spam to drive visitors to any other site hosted
                    on or through Our systems;</li>
                <li>(o) shall create liability for us or cause us to lose (in whole or part) the services of our
                    Internet Service Provider ("ISPs") or other Users;</li>
                <li>(p) contains any content which is non-compliant with the Information Technology Act, 2000, Rules and
                    regulations, guidelines made thereunder; or</li>
                <li>(q) violates any law for the time being in force.</li>
            </ul>

            <p>7.2 You further agree to make use of the Platform in a bona fide manner. In particular, You agree not to:
            </p>
            <ul>
                <li>(a) print, distribute, share, download, duplicate or otherwise copy, delete, vary or amend or use
                    any data or information posted by any User other than You;</li>
                <li>(b) use or attempt to use another person's Profile;</li>
                <li>(c) attempt to gain unauthorized access to any portion or feature of the Platform, or any other
                    systems or networks connected to the Platform;</li>
                <li>(d) probe, scan or test the vulnerability of the Platform or any network connected to the Platform
                    or breach the security or authentication measures on the Platform;</li>
                <li>(e) disrupt or interfere with the security of, or otherwise cause harm to, the Platform, systems
                    resources, accounts, passwords, servers or networks;</li>
                <li>(f) use any automated systems to extract data from the Platform;</li>
                <li>(g) make any inaccurate, false, unfair or defamatory statement(s) or comment(s) about Us or the
                    brand name or domain name used by Us;</li>
                <li>(h) make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand
                    name used by Us, or otherwise engage in any conduct that might tarnish the image or reputation of
                    Hyderabad Constructions Companies or Hyderabad Constructions;</li>
                <li>(i) take any action that imposes an unreasonable or disproportionately large load on the
                    infrastructure of the Platform or Our systems or networks;</li>
                <li>(j) circumvent or manipulate our Platform, Platform Services, registration process, billing system,
                    or attempt to do so;</li>
                <li>(k) engage in commercial activities and / or sales without Our prior written consent such as
                    contests, sweepstakes, barter, advertising and pyramid schemes;</li>
                <li>(l) engage in deceptive, fraudulent, anti-competitive practices or other invalid means to meet the
                    other User's requirements;</li>
                <li>(m) engage in any form of fraudulent traffic generating methods including use of robots, spiders,
                    auto-spawning browsers, auto reloading, meta refreshes or any other form of fraudulent and
                    artificial traffic;</li>
                <li>(n) use the Platform for any purpose that is unlawful or prohibited by the Terms of Use; or</li>
                <li>(o) violate any applicable laws or regulations for the time being in force within or outside India.
                </li>
            </ul>

            <p>7.3 You shall at all times ensure full compliance with the applicable provisions of the Information
                Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all
                applicable domestic laws, rules and regulations regarding Your use of the Platform. You shall not engage
                in any transaction in an item or service, which is prohibited by applicable law.</p>

            <p>7.4 You shall solely be responsible for maintaining the necessary computer / mobile equipment, internet
                connections and other software and technologies that may be required to access, use and transact on the
                Platform. You may incur access or data fees from third parties in connection with your purchase and/or
                use of the services. You are responsible for all such fees.</p>

            <p>7.5 You hereby expressly agree that any Services availed by the You will not be bartered or in any way
                used for any commercial purposes or for profit. Accordingly, Hyderabad Constructions reserves the right to cancel any
                orders that classify as 'Business Use' as determined by Hyderabad Constructions, including but not limited to:</p>
            <ul>
                <li>(a) Services availed for commercial use and not for self-consumption;</li>
                <li>(b) Multiple orders placed for same Services at the same address;</li>
                <li>(c) Invalid address given in order details; or</li>
                <li>(d) Any malpractice used to place the order.</li>
                <li>(e) There may be certain orders that Hyderabad Constructions is unable to process or pass on User's order to the
                    Contractor and must cancel. Some situations that may result in Hyderabad Constructions's inability to process or
                    pass on User's order include, without limitation, non-availability of the Platform, force majeure,
                    credit limitations or suspected fraud.</li>
            </ul>

            <p>7.6 You shall use this Platform, and any voucher/coupons purchased through it, for personal,
                non-commercial use only and shall not re-sell the same to any other person.</p>

            <p>7.7 You may need to install updates that we or any third party introduces from time to time to use the
                Services including downloads and required functionality, such as bug fixes, patches, enhanced functions,
                missing plug-ins and new versions (collectively, <strong>"Updates"</strong>). Your use of the Platform
                you have installed requires that you have agreed to receive such automatically requested Updates.</p>

            <p>7.8 The Platform may allow you to post certain content, data or information of Your own such as allowing
                You to rate Services, Contractors etc. on specific pages of the Platform (collectively referred to
                <strong>"Posted Content"</strong>). You, being the originator of the Posted Content, are responsible for
                the Posted Content that You upload, post, publish, transmit or otherwise make available on the Platform.
                You represent that you have obtained all relevant consents and approvals in order to post any Posted
                Content. Hyderabad Constructions reserves the right to disable access to the Posted Content on the Platform.
            </p>

            <p>7.9 Unless otherwise specified, the Services provided on the Platform is presented solely for use in
                India. Hyderabad Constructions makes no representation that the Services offered on the Platform are appropriate or
                available for use in other locations other than India.</p>

            <hr class="section-divider">

            <!-- Section 8 -->
            <h2>8. Payment</h2>

            <p>8.1 Presently, Hyderabad Constructions does not levy any fee for browsing the Platform. Hyderabad Constructions may charge You certain
                fees for the use of the Platform and Services as a whole, or certain features of the Platform/Services.
                You agree to pay any such fees, as may be applicable to the Services that You use. You agree that Hyderabad Constructions
                One may, at any time, charge, modify or waive fees required to use the Platform. Your continued use of
                the Platform / Services after such change in the fees will be considered to be Your acceptance of such
                changes.</p>

            <p>8.2 You agree to provide correct and accurate financial information, such as credit/debit card details to
                the approved payment gateway or pre-paid payment instrument account details or net banking or e-wallet
                details for availing Services on the Platform. The information provided by You will not be utilized or
                shared with any third party unless required in relation to fraud verifications or by law, regulation or
                court order. Hyderabad Constructions expressly disclaims all liabilities that may arise as a consequence of any
                unauthorized use of Your credit/ debit card or pre-paid instrument account or net banking details or
                e-wallet.</p>

            <p>8.3 You agree that the Transactions, transaction price and all commercial terms such as provision of
                Services are principal to principal bipartite contractual obligations between the User and the
                Contractors listed on the Platform, and the payment management and coordination facilities offered by
                Hyderabad Constructions are merely platform services used by the Users to facilitate the Transaction.</p>

            <p>8.4 You acknowledge that Hyderabad Constructions as an ecommerce platform is required to deduct TCS on GST as per CGTS
                Act 2017 and TDS as per Income Tax Act 1961. All payment to the Contractors shall be made net of such
                deductions as applicable.</p>

            <p>8.5 Users may be required to pay additional charges / fees for Services availed by them on the Platform.
                Use of the payment facility shall not render Hyderabad Constructions liable or responsible for non-delivery,
                non-receipt, non-payment, breach of representations and warranties, non-provision of services or
                warranty services or fraud as regards the Services listed and/or offered on the Platform.</p>

            <p>8.6 All payments made against the provision of Services on the Platform shall compulsorily be in Indian
                Rupees or such other currencies as may be notified by the Platform from time to time. The Platform
                facilitates payments through one or more of: (i) net banking, (ii) NEFT, (iii) RTGS (iv) credit / debit
                card; (v) cheque and (vi) e-wallets or any other facilities as made available by Hyderabad Constructions from time to
                time.</p>

            <p>8.7 You hereby specifically authorize Hyderabad Constructions or its service providers to collect, process, facilitate,
                and remit payments and / or the transaction price electronically or by cheque, as the case may be, to
                and from You in respect of Transactions through payment facility.</p>

            <p>8.8 <strong>Bank Instruments and Transfers:</strong> All online bank transfers (NEFT and RTGS) from valid
                bank accounts and cheque payments are processed using the payment gateway provided by the respective
                issuing bank. All such online bank transfers and cheque payments on payment facility are also governed
                by the terms and conditions agreed to between the Users and the respective issuing bank.</p>

            <p>8.9 <strong>Credit / Debit cards:</strong> All valid credit / debit / cash card / and other payment
                instruments are processed using a credit card payment gateway or appropriate payment system
                infrastructure and the same will also be governed by the terms and conditions agreed to between Users
                and the respective issuing bank and payment instrument issuing company.</p>

            <p>8.10 <strong>E-wallets:</strong> Payments through e-wallets are processed through third party service
                providers. The same will also be governed by the terms and conditions agreed to between Users and the
                respective payment instrument issuing company.</p>

            <p>8.11 Users may also avail of financing facilities from financial partners on the Platform. In case a
                financial partner fails to disburse monies when required by the Platform on an order placed by You, You
                shall be liable to make such payment as and when demanded by Hyderabad Constructions. In case of any breach of terms by
                You with respect to the financing availed on the Platform, We reserve the right to suspend your account
                in the Platform.</p>

            <p>8.12 Hyderabad Constructions may have existing arrangements with banks, regarding limits on the amounts You can pay in
                the course of a single transaction. Hyderabad Constructions shall be under no liability whatsoever in respect of any
                loss or damage arising directly or indirectly out of the decline of authorization for any transaction.
            </p>

            <p>8.13 Hyderabad Constructions, at its sole discretion, may from time to time, and pursuant to applicable laws, provide
                credit support in the form of first loss default guarantee or such other means as deemed appropriate to
                facilitate third party financing. In case Hyderabad Constructions has provided such credit support on the financing
                availed by You, and You fail to make required payments, Hyderabad Constructions shall have the right to recover such
                defaulted amount to the extent of the guarantee.</p>

            <p>8.14 Where no credit support provided by Hyderabad Constructions with respect to financing availed by You, Hyderabad Constructions will
                not be responsible in any manner, for the obligations of the Users under such financial arrangements
                between the Users and the financial partners.</p>

            <p>8.15 You understand, accept, and agree that the payment facility provided by Hyderabad Constructions is neither a banking
                nor financial service, and that Hyderabad Constructions is merely a Service Provider providing an electronic, automated
                online electronic payment facility for receiving payment through cash, collection and remittance for
                transactions on the Platform using the existing authorized banking infrastructure and credit card
                payment gateway network.</p>

            <p>8.16 You shall comply with all applicable laws (including without limitation Foreign Exchange Management
                Act, 1999, Customs Act, Information and Technology Act, 2000, Prevention of Money Laundering Act, 2002,
                Foreign Contribution Regulation Act, 1976, Income Tax Act, 1961, and Export Import Policy of government
                of India) applicable to them respectively for using payment facility and Platform.</p>

            <hr class="section-divider">

            <!-- Section 9 -->
            <h2>9. Intellectual Property</h2>

            <p>9.1 The intellectual property in the Platform, and in the material, content and information made
                available on the Platform including building designs, graphics, images, photographs, logos, trademarks,
                the appearance, organisation and layout of this Platform and the underlying software code belong to Us
                or Our licensors. You must not copy, modify, alter, publish, broadcast, distribute, sell or transfer
                (whether in whole or in part) any of material referred to above.</p>

            <p>9.2 You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary
                information (including images, text, page layout, or form) of Hyderabad Constructions without our prior written consent.
                You may not use any meta tags or any other "hidden text" utilising Hyderabad Constructions's or its affiliates' names or
                trademarks without the prior written consent of Hyderabad Constructions and / or its Affiliates, as applicable.</p>

            <p>9.3 All material on the Platform including images, illustrations, audio clips, and video clips, are
                protected by copyrights, trademarks and other intellectual property rights. You must not copy,
                reproduce, republish, upload, post, transmit, or distribute any material in any way, including by email
                or other electronic means and whether, directly or indirectly.</p>

            <hr class="section-divider">

            <!-- Section 10 -->
            <h2>10. User Content</h2>

            <p>You grant Us license to use and modify all User Content in which You may hold any intellectual property
                rights. We can, consistent with Our Privacy Policy, use the User Content, including for creating
                databases, creating derivative works, analysing data, analysing trends and usage, and in any other
                manner.</p>

            <hr class="section-divider">

            <!-- Section 11 -->
            <h2>11. Contents Posted on the Platform</h2>

            <p>11.1 The Platform and the processes, and their selection and arrangement, including but not limited to
                the text, graphics, user interfaces, visual interfaces, sounds and music (if any), artwork and computer
                code on the Platform is owned and controlled by Hyderabad Constructions or its licensors and the design, structure,
                selection, coordination, expression, look and feel and arrangement of such content is protected by
                copyright, patent and trademark laws, and various other intellectual property rights. Through Your use
                of the Platform, by no means are any rights impliedly or expressly granted to You in respect of such
                content.</p>

            <p>11.2 You may use information on the Services purposely made available on the Platform for downloading,
                provided that You (a) do not remove any proprietary notice language in all copies of such documents, (b)
                use such information only for Your personal, non-commercial informational purpose and do not copy or
                post such information on any networked computer or broadcast it in any media, (c) make no modifications
                to any such information, and (d) do not make any additional representations or warranties relating to
                such documents.</p>

            <p>11.3 Any software that is available on the Platform is the property of Hyderabad Constructions or its vendors. You may
                not use, download or install any software available at the Platform, unless otherwise expressly
                permitted by the Terms of Use or by the express written permission of Hyderabad Constructions.</p>

            <hr class="section-divider">

            <!-- Section 12 -->
            <h2>12. Privacy Policy</h2>

            <p>12.1 Any personal information You supply to Us when You use this Platform will be used in accordance with
                Our <a href="privacy-policy.html">Privacy Policy</a>. The personal information / data provided to Us by
                You during the course of Your usage of the Platform will be treated as strictly confidential and shall
                be used in accordance with the Privacy Policy and Terms of Use (<strong>"ToU"</strong>) and applicable
                laws and regulations.</p>

            <hr class="section-divider">

            <!-- Section 13 -->
            <h2>13. Infringement and Take Down Policy</h2>

            <p>13.1 We are committed to removing listing or content on the Platform which infringes any intellectual
                property rights of others. In the event that You believe that Your intellectual property right has been
                infringed by any of our Users, please email Us immediately at <a
                    href="mailto:team@hyderabadconstructions.in">team@hyderabadconstructions.in</a> along with the information set
                out below:</p>
            <ul>
                <li>(a) Description of the alleged intellectual property right that has been infringed along with
                    adequate information to identify the intellectual property, including URL or screen shots of the
                    listing / content on our Platform;</li>
                <li>(b) Details establishing that the complainant is the owner or the exclusive licensee of the
                    infringed intellectual property;</li>
                <li>(c) Details of the person, if known who is responsible for uploading the listing / content,
                    infringing Your intellectual property;</li>
                <li>(d) A statement by you that you have a good faith belief that the use of the material complained of
                    is not authorized by the copyright or intellectual property owner, its agent, or the law;</li>
                <li>(e) A statement by you, that the information in your notice is accurate and that you are the
                    copyright or intellectual property owner or authorized to act on the copyright or intellectual
                    property owner's behalf.</li>
                <li>(f) Undertaking that You will file an infringement suit in a competent court against the User
                    responsible for uploading the infringing intellectual property, and undertaking that You shall
                    produce the orders of the court to Us within 21 days from the date of receipt of infringement
                    notice; and</li>
                <li>(g) Your address, telephone number, and email address.</li>
            </ul>

            <p>13.2 We will respond to all infringement notices and will comply with all applicable law in relation to
                the take down of such listings or content on the Platform. We also reserve the right to terminate a
                User's account if the User is guilty of such infringement.</p>

            <p>13.3 When You send Us an infringement notice, You: (i) declare that all statements made by You are true;
                (ii) acknowledge and agree that We may share Your infringement notice with third parties including the
                parties involved in the allegedly objectionable activities; (iii) agree to indemnify Us against all
                claims which may arise in connection with such an infringement notice being made by You.</p>

            <p>13.4 On receipt of Your notice, we will verify the allegations and if We find that the alleged listing /
                content is infringing Your intellectual property rights, We shall remove the listing / content promptly
                upon such determination.</p>

            <p>13.5 We may take such action as we deem appropriate in keeping with our policies and applicable law which
                may include, asking further details from you or taking down the content that was the subject matter of
                Your infringement notice.</p>

            <p>13.6 Hyderabad Constructions has the right to restore listing of the services in the event that You are unable to produce
                the orders of the competent court having jurisdiction as set out above.</p>

            <hr class="section-divider">

            <!-- Section 14 -->
            <h2>14. Breach of these Terms of Use</h2>

            <p>If You have, or if We have reasonable grounds to believe that You have, violated these Terms of Use or
                any Agreements or any other additional terms that apply to You, We reserve the right to suspend or
                terminate Your access to the Platform at any time, forfeit any amounts paid by You, take all such
                remedies available to Us and report such action to relevant authorities.</p>

            <hr class="section-divider">

            <!-- Section 15 -->
            <h2>15. Third Party Content</h2>

            <p>15.1 Notwithstanding its reasonable efforts in that behalf, Hyderabad Constructions cannot take responsibility or control
                the information such as catalogues, description and specifications, lists of dealers, reports on news,
                entertainment, technology and features, advertisements including videos, images and photographs of the
                products, links to third party websites and other data from external sources provided by third parties
                on the Platform (<strong>"Third Party Content"</strong>). All Third Party Content is provided on an 'As
                Is' basis.</p>

            <p>15.2 Hyderabad Constructions shall not be held liable for any loss suffered by You based on Your reliance on or use of
                such Third Party Content.</p>

            <p>15.3 All third party advertisements, hyperlinks or other redirection tools on the Platform which take You
                to content operated by third parties are not controlled by Us and do not form part of the Platform. We
                are not liable for any loss or harm that may occur to You as a result of such sites.</p>

            <hr class="section-divider">

            <!-- Section 16 -->
            <h2>16. Disclaimer and Limitation of Liability</h2>

            <p>16.1 The Platform is provided on an "as is" and "as available" basis without any representation or
                warranty, express or implied. We do not warrant that:</p>
            <ul>
                <li>(a) the Platform will be constantly available, or available at all. We shall have no liability to
                    You for any interruption or delay in access to the Platform, irrespective of the cause;</li>
                <li>(b) the results that may be obtained from the use of the Platform or Services will be effective,
                    accurate or reliable;</li>
                <li>(c) the quality of the Platform or Services will meet your expectations;</li>
                <li>(d) any errors or defects in the Platform or Services will be corrected;</li>
                <li>(e) the information on the Platform is complete, true, reliable, current, accurate or
                    non-misleading;</li>
                <li>(f) that the Platform is secure or free of viruses, trojans or other malware; or</li>
                <li>(g) the contents of the Platform do not infringe any intellectual property rights.</li>
            </ul>

            <p>16.2 We shall not be liable for any direct, special, punitive, incidental, indirect or consequential
                damages including but not limited to any loss of profits, revenue, contracts, anticipated savings,
                goodwill, expenditure, business or data of any kind in connection with these Terms of Use, or any
                Transactions that occur on the Platform. Our combined liability (if any) for any losses or claims
                arising out of any Transaction conducted using the services of the Platform shall not exceed the total
                fees paid to Us directly by the User for such Transaction.</p>

            <p>16.3 Hyderabad Constructions neither recommends You to avail the construction services of any Contractor on the Platform
                nor does Hyderabad Constructions endorse, control or accept any responsibility for any such services offered by the
                Contractor and/or other Service Providers on the Platform.</p>

            <p>16.4 Notwithstanding anything contrary contained in this Terms of Use and/or the Agreement, Hyderabad Constructions is
                and shall not be responsible for any services rendered by the third-party Contractors and/or any other
                Service Providers listed on the Platform.</p>

            <p>16.5 You understand and agree that any material or data downloaded or otherwise obtained through the
                Platform is done entirely at Your own discretion and risk and You will be solely responsible for any
                damage to their computer systems or loss of data that results from the download of such material or
                data.</p>

            <p>16.6 You expressly understand and agree that, to the maximum extent permitted by applicable law Hyderabad Constructions
                will not be liable for any loss that you may incur as a consequence of unauthorized use of your account
                or account information in connection with the Platform or any Services, either with or without your
                knowledge.</p>

            <p>16.7 In the event You have purchased / downloaded the Purchase from any online application stores,
                whether provided by Apple, Inc., Google, Inc. or Blackberry Limited (or their respective affiliates)
                (collectively referred to as <strong>"Store Providers"</strong>), the Store Providers shall not be
                liable for any (i) warranty obligations of Hyderabad Constructions and related claims; (ii) product liability / consumer
                protection claims; and (iii) any third party claims of infringement of intellectual property rights by
                the Platform/Hyderabad Constructions.</p>

            <p>16.8 You understand, agree and acknowledge that Platform uses third party service providers to store and
                process Your personal information and other information which You provide to the Platform and such third
                parties may store and process your personal information in a country or state which may not have
                jurisdiction over You. You agree and understand that Platform provides no guarantee, warranty or
                assurance that such third party service providers will protect Your personal information.</p>

            <p>16.9 Pursuant to the provisions of the Foreign Exchange Management Act, 1999, and applicable laws, the
                Platform may provide certain support services to facilitate the transactions between users of the
                Platform. The Platform will not be held liable or responsible towards You for any actions, commission,
                omission, misconduct, fraud or negligence of these third parties unless directly caused by misconduct
                and gross negligence of the Platform.</p>

            <p>16.10 Hyderabad Constructions's entire and aggregate liability in any circumstance including these terms and conditions
                shall not exceed the greater of Indian Rupees One Hundred (INR 100) or the amount of fees, if any, paid
                by You to Hyderabad Constructions under the relevant order to which the cause of action for the liability related.</p>

            <p>16.11 In addition to any limitation of liability and various disclaimers provided elsewhere in this Terms
                of Use, Hyderabad Constructions's entire liability and Your sole and exclusive remedy in any circumstance is limited to
                exercise its reasonable efforts to enable to You get the refund of the services from the Contractor on
                the Platform.</p>

            <hr class="section-divider">

            <!-- Section 17 -->
            <h2>17. Indemnity</h2>

            <p>17.1 You agree to indemnify Hyderabad Constructions, its Affiliates and its licensors, subsidiaries, group companies (as
                applicable) and their respective officers, directors, agents, and employees, on demand, against any
                claim, action, damage, loss, liability, cost, charge, expense or payment which We may pay, suffer, incur
                or are liable for, in relation to any act You do or cause to be done, in breach of the Terms of Use or
                any additional terms applicable to You or Your violation of any law, rules or regulations (including
                infringement of intellectual property rights) of a third party.</p>

            <p>17.2 Hyderabad Constructions may notify You of any claims which You shall be liable to indemnify Hyderabad Constructions against. You
                will then be required to consult with Hyderabad Constructions regarding the course of action to be undertaken in
                defending such a claim. Further, You shall not compromise or settle any claim or admit any liability or
                wrongdoing on the part of Hyderabad Constructions without the express prior written consent of Hyderabad Constructions.</p>

            <hr class="section-divider">

            <!-- Section 18 -->
            <h2>18. Feedback and Information</h2>

            <p>18.1 Any feedback You provide to this Platform shall be deemed to be non-confidential. Hyderabad Constructions shall be
                free to use such information on an unrestricted basis. Further, by submitting the feedback, You
                represent and warrant that (i) Your feedback does not contain confidential or proprietary information of
                You or of third parties; (ii) Hyderabad Constructions is not under any obligation of confidentiality, express or
                implied, with respect to the feedback; (iii) Hyderabad Constructions may have something similar to the feedback already
                under consideration or in development; and (iv) You are not entitled to any compensation or
                reimbursement of any kind from Hyderabad Constructions for the feedback under any circumstances.</p>

            <p>18.2 To clarify, Hyderabad Constructions may at its discretion, make any modifications or changes to the
                Platform/Services on the basis of such feedback, however Hyderabad Constructions is not obliged to do so. You expressly
                waive any and all rights in such changes or modifications to the Platform/Services, and assign to Hyderabad Constructions
                One, all worldwide rights and title (including any intellectual property rights) to such changes or
                modifications to the Platform/Services, in perpetuity.</p>

            <hr class="section-divider">

            <!-- Section 19 -->
            <h2>19. Amendments to the Terms of Use</h2>

            <p>We may amend or replace these Terms of Use, and other Agreements / policies on the Platform from time to
                time, by updating this document. Your use of the Platform following the posting of changes will mean
                that You accept such changes.</p>

            <hr class="section-divider">

            <!-- Section 20 -->
            <h2>20. Severability and Waiver</h2>

            <p>If any provisions of these Terms of Use are found to be invalid by any court having competent
                jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions
                of these Terms of Use, which shall remain in full force and effect. No waiver of any term of these Terms
                of Use shall be deemed a further or continuing waiver of such term or any other term.</p>

            <hr class="section-divider">

            <!-- Section 21 -->
            <h2>21. Relationship between Us and Users</h2>

            <p>Neither usage nor registration on the Platform creates an association, partnership, venture or
                relationship of principal and agent, master and servant or employer and employee between the User and
                Us.</p>

            <hr class="section-divider">

            <!-- Section 22 -->
            <h2>22. Assignment</h2>

            <p>You cannot assign or otherwise transfer the Terms of Use, or any rights granted hereunder or any
                obligations, to any third party and any such assignment or transfer or purported assignment or transfer
                shall be void ab initio. Hyderabad Constructions's rights and/or obligations under the Terms of Use are freely
                assignable or otherwise transferable by Hyderabad Constructions to any third parties without the requirement of seeking
                Your prior consent.</p>

            <hr class="section-divider">

            <!-- Section 23 -->
            <h2>23. Force Majeure</h2>

            <p>If performance of any service or obligation under these Terms of Use or other Agreement by Hyderabad Constructions is
                prevented, restricted, delayed or interfered with by reason of labor disputes, strikes, acts of God,
                floods, lightning, severe weather, shortages of materials, rationing, utility or communication failures,
                earthquakes, war, revolution, acts of terrorism, civil commotion, acts of public enemies, blockade,
                embargo or any law, order, proclamation, regulation, ordinance, demand or requirement having legal
                effect of any government or any judicial authority (each, a <strong>"Force Majeure Event"</strong>),
                then Hyderabad Constructions shall be excused from such performance to the extent of and during the period of such Force
                Majeure Event. Hyderabad Constructions shall exercise all reasonable commercial efforts to continue to perform its
                obligations hereunder.</p>

            <hr class="section-divider">

            <!-- Section 24 -->
            <h2>24. Applicable Law, Jurisdiction and Dispute Resolution</h2>

            <p>24.1 This Terms of Use shall in all respects be governed by and construed in accordance with the laws of
                India, without giving effect to conflict of law principles and the Parties agree to submit to the
                exclusive jurisdiction of the appropriate courts at Mumbai (India).</p>

            <p>24.2 If any dispute between the parties arises out of or in connection with this Terms of Use, inter alia
                including the breach, termination or invalidity thereof (<strong>"Dispute(s)"</strong>), the parties
                shall, before initiating any legal proceedings, use all reasonable endeavors to negotiate and amicably
                settle the Dispute within 30 (thirty) days of a party serving the other party with a notice that a
                Dispute has arisen.</p>

            <p>24.3 If the parties fail to amicably resolve the Dispute as per clause 24.2, then the Dispute shall be
                referred to arbitration and shall be exclusively and finally determined by arbitration conducted in
                accordance with the provisions of the Arbitration and Conciliation Act, 1996 (<strong>"Act"</strong>),
                as amended from time to time. The arbitration proceedings shall be conducted by a sole arbitrator to be
                appointed with mutual consent of the parties. The seat and venue of arbitration shall be Mumbai. The
                arbitration proceedings shall be conducted in English language.</p>

            <p>24.4 Notwithstanding provisions under clause 24.3, the parties agree to conduct the arbitration
                proceedings remotely and virtually through video conferencing, for more expeditious resolution of the
                dispute in the interest of time. The provisions pertaining to 'Fast Track Proceedings' under section 29B
                of the Act shall be applicable to the arbitration proceedings invoked under this clause.</p>

            <p>24.5 The Arbitral Tribunal shall conduct the arbitration proceedings in a speedy manner and shall pass
                its award expeditiously, in writing with detailed reasoning therein. The award passed by the Arbitral
                Tribunal shall be confidential and conclusive and the parties agree to be bound thereby and to act
                accordingly.</p>

            <p>24.6 The Arbitral Tribunal constituted under this Agreement may consolidate the hearing of Disputes under
                arbitration, if it determines that (i) there are issues of fact or law common to the proceedings such
                that a consolidated proceeding would be more efficient than multiple separate proceedings, and (ii) no
                party would be prejudiced as a result of such consolidation through undue delay or otherwise.</p>

            <p>24.7 Notwithstanding the existence of any Dispute or commencement of any arbitration proceedings, the
                rights and obligations of the parties under this Agreement shall remain valid and enforceable. The
                parties shall continue to perform and fulfil their respective rights and obligations under this
                Agreement, unless the same is impossible without resolution of the said dispute.</p>

            <hr class="section-divider">

            <!-- Section 25 -->
            <h2>25. Grievance Officer</h2>

            <p>Users can access, modify, correct and eliminate the data about him/her/it which has been collected
                pursuant to his/her/its decision to become a User. If you believe that your rights are being infringed
                or you have any grievances, complaints or concerns, including in relation to the information shared by
                the User with Hyderabad Constructions on the Platform, you may reach out to our grievance officer through telephonic or
                electronic mode in the following manner:</p>

            <p>
                <strong>Name:</strong> ER MOHAMMED ABBAS<br>
                <strong>Address:</strong> 13-6-437/A/98/3, Khader Bagh, Tolichowki, Hyderabad.<br>
                <strong>Email:</strong> <a href="mailto:team@hyderabadconstructions.in">team@hyderabadconstructions.in</a><br>
                <strong>Phone Number:</strong> <a href="tel:+919703879886">+91 97038 79886</a>
            </p>

            <p>We respond expeditiously to rights owners and their agents who communicate their concerns about any
                alleged infringement in the manner provided under these Terms of Use.</p>

        </div>
    </section>

    <?php include 'includes/action-buttons.php'; ?>
    <?php include 'includes/footer.php'; ?>
    <?php include 'includes/book-meeting-popup.php'; ?>

    <script src="assets/js/script.js"></script>

</body>

</html>